Frontend cleanup
googleinterns/recomator pull request #113
Opened 2020-08-21 08:59 UTC by s17k

### Not quite ready yet.

2020-08-24 09:53 UTC, s17k commented
Just to clarify, the file `model.ts` was split into `recommendation_raw.ts` and `recommendation_extra.ts`. The related added lines are not actually new.

2020-08-25 08:10 UTC, Podkamienna commented on frontend/src/components/Footer.vue
> +            Cancel
Why do you think that blue is better for the cancel button?

2020-08-25 08:10 UTC, Podkamienna commented on frontend/src/components/Footer.vue
> +            <v-icon>mdi-check</v-icon>
Is that possible for the icons to be a bit higher, so that the text is in the middle of them? I know, that's just a minor detail, but it doesn't look right in my opinion.

2020-08-25 08:58 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  // headers ending with "Col" have values that are bound to corresponding columns
I am not a fan of consistency for the sake of consistency.
It is sometimes nice to have a certain decorum, but usually it also helps you differentiate between let's say class names and interface names. That is not the case here.

2020-08-25 09:00 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  // Sync selected with the store
Yes, https://dictionary.cambridge.org/dictionary/english/sync

2020-08-25 09:06 UTC, s17k commented on frontend/src/components/Footer.vue
> +            Cancel
Because a red button associates with something really important (if you google 'nuclear button', all buttons are red). Blue is the colour that we use for nearly all other buttons (`primary`).

2020-08-25 09:10 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  // Sync selected with the store
It is extremely common in programming slang.

2020-08-25 09:12 UTC, s17k commented on frontend/src/components/Footer.vue
> +            <v-icon>mdi-check</v-icon>
Nicely spotted, should be doable.

2020-08-25 09:34 UTC, Podkamienna commented on frontend/src/components/Footer.vue
> +            Cancel
Ok, that may be a good way to think about it.

2020-08-25 10:00 UTC, Podkamienna approved these changes

2020-08-25 10:01 UTC, merged

2020-08-25 12:10 UTC, brzezinski requested changes
please review comments and update

2020-08-25 12:10 UTC, brzezinski commented on frontend/src/components/Footer.vue
> +            Cancel
agree