Frontend applied
googleinterns/recomator pull request #117
Opened 2020-08-24 08:21 UTC by Podkamienna

2020-08-24 08:36 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    for (const row of this.selectableRows) {
You can make this a one-liner with [every()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every)

2020-08-24 08:42 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    } else {
This has a potential to be quite slow, really and it's not obvious why is it done here.
Why not just add a one-line mutation to the store (let's say `addSelectedRow` and use it)

2020-08-24 08:47 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    } else {
You could also use it in `selectAll`

2020-08-24 08:49 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
If it keeps all recommendations that are selected, why is it called `selectableRows` and not `selectedRows` ?

2020-08-24 08:50 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
No, it keeps all the recommendations from the current view, that can be selected. And it is needed for checking if all the recommendations are selected. I couldn't come up with a better way, but I am open for suggestions.

2020-08-24 08:54 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
I forgot to change the comment

2020-08-24 08:54 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +
I would avoid calling it `value`, as it hardly explains what it actually is (hard to guess without looking at the code, my initial guess was actually wrong).
Why not call it `delete` or `toDelete` or `remove` or something like that ?

2020-08-24 08:55 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +    } else {
I agree that it's better to add the mutation to the store.

2020-08-24 08:57 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  pagination(page: any) {
It is quite hard to guess what this returns without remembering how the `pagination` slot works.

2020-08-24 09:06 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  selectableRows = new Array<RecommendationExtra>();
It's not a rule, but it would be best to keep as much as possible in Vuex stores so that application state can be more easily tracked. Also, importing individual function from `.vue` files is a pain (at least I couldn't find a neat way), so probably best for all the logic that needs to be tested to be in stores.

2020-08-24 09:39 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    <template v-slot:header.data-table-select="{}">
This overwrites the default behaviour which shows a minus if there is a mix of selected and not selected. I checked and Gmail has the exact same behaviour. I would trust their UX team.
You can just show an icon or button with an icon instead if that is the case.

2020-08-24 09:42 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
Maybe I am missing something, but couldn't you iterate over all recommendations from the page and just check their status to see if they are _selectable_ or not ?

2020-08-24 09:45 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +    <template v-slot:header.data-table-select="{}">
I didn't notice that. It's easy to just show the minus in the right case.

2020-08-24 09:54 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  pagination(page: any) {
What do you mean by "this"? Is this a suggestion to create some type of which page would have to be? Or do you have something else in mind?

2020-08-24 09:56 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +  pagination(page: any) {
I meant that I think a name such as `pageChangedHandler` would make what this is doing  more obvious

2020-08-24 09:58 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
I really wanted to do it that way, but I couldn't find a way to. If know how to do that, it would be great to change it.

2020-08-24 10:01 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
To be more precise, I couldn't find a way to get  the list of rows that are currently visible.

2020-08-24 11:42 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +  // Array that keeps all recommendations that are selected
Ok, I found it.

2020-08-25 09:18 UTC, s17k requested changes
otherwise looks good!

2020-08-25 09:18 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.every(this.isSelected);
I am a bit surprised that this even works: https://stackoverflow.com/questions/30486345/losing-this-context-in-javascript-when-passing-around-members

2020-08-25 09:18 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.every(this.isSelected);
If you pass `() => this.isSelected` instead, then `this` will be captured in this anonymous function and it will be a bit clearer why this works.

2020-08-25 09:30 UTC, s17k approved these changes

2020-08-25 15:32 UTC, minorczyka requested changes

2020-08-25 15:32 UTC, minorczyka commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.every(() => this.isSelected);
I'm not a JS expert but shouldn't it be either `this.selectableRows.every(this.isSelected);` or `this.selectableRows.every(row => this.isSelected(row));`?

2020-08-25 15:32 UTC, minorczyka commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.some(item => this.selectedRows.includes(item));
If you declared `isSelected` function, you should probably use it here.

2020-08-25 15:32 UTC, minorczyka commented on frontend/src/components/CoreTable.vue
> +    v-on:current-items="setSelectableRows"
Using this `setSelectableRows` we're getting a little bit weird dependency. Table depends on recommendatoins from store and store depends on what is displayed in table. But I guess there's no other easy solution for this problem.

2020-08-25 15:56 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.every(() => this.isSelected);
Nicely spotted, no wonder I missed it in the review as I actually suggested it...

2020-08-26 07:37 UTC, Podkamienna commented on frontend/src/components/CoreTable.vue
> +    return this.selectableRows.every(() => this.isSelected);
I have no idea, why I didn't notice it, as it simply doesn't work...

2020-08-27 17:09 UTC, minorczyka approved these changes

2020-08-28 06:37 UTC, merged