add real service
googleinterns/recomator pull request #122
Opened 2020-08-25 08:48 UTC by ViktoriiaKovalova

authorization & listing. /apply was not added yet.

2020-08-31 06:39 UTC, ViktoriiaKovalova commented
it's not building because automation package changes are not in master yet. please review `real-service-automation-part` first

2020-08-31 08:57 UTC, s17k commented on cmd/server/apply.go
> +		if len(authCode) != 0 {
it's not that easy to read 4 nested ifs - the else's are usually far away from conditions.
If you changed this and the next `if` to their opposites (e.g. `len(authCode) == 0`), that would remove the two extra levels.

2020-08-31 09:49 UTC, ViktoriiaKovalova commented on cmd/server/apply.go
> +		if len(authCode) != 0 {
thanks, fixed

2020-09-02 13:57 UTC, minorczyka requested changes

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/list.go
> +		handler, loaded := listRequestsInProcess.LoadOrStore(user.email, &listRequestHandler{service: user.service, numConcurrentCalls: defaultNumConcurrentCalls})
Returned `listRequestHandler` is not thread-safe but you're accessing it from multiple threads.

One possible scenario when it won't work is when `h.task` is already incremented to max in `ListAllProjectsRecommendations` but function still haven't returned its result. In L105 you will get empty results from `handler.GetResult()`.

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/main.go
> +	if err := setConfig(&config, "config.json"); err != nil {
Reading credentials from file might be troublesome when deploying to AppEngine. We might want to read it from environmental variables or maybe use some dedicated solution for secrets from AppEngine. But let's leave it as it is for now.

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/apply.go
> +/*
I haven't reviewed this file because there's the same problem with synchronization as in `list.go` so some changes will be needed.

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/auth.go
> +			sendError(c, fmt.Errorf("Auth code not specified"), http.StatusUnauthorized)
It should be rather BadRequest error here, user was authorized to access this page.

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/auth.go
> +	token := request.Header["Authorization"]
Convention for using Authorization header is: `Authorization: <type> <credentials>` (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization).

We don't really have to but we probably should follow this convention and include `Bearer` type.

2020-09-02 13:57 UTC, minorczyka commented on cmd/server/auth.go
> +	email := c.Query("login_hint")
It would be nice to add comment about this query parameter either here or when you're configuring gin's router.

2020-09-02 14:22 UTC, ViktoriiaKovalova commented on cmd/server/list.go
> +		handler, loaded := listRequestsInProcess.LoadOrStore(user.email, &listRequestHandler{service: user.service, numConcurrentCalls: defaultNumConcurrentCalls})
It is actually done only when result is already assigned(53-54 lines in this file):
```
h.result, h.err = automation.ListAllProjectsRecommendations(h.service, h.numConcurrentCalls, h.task.GetNextSubtask())
h.task.SetAllDone()
```
And GetProgress() will always return (done, all) such that `done < all` until SetAllDone() method was called (from Task implementation).

2020-09-02 14:25 UTC, ViktoriiaKovalova commented on cmd/server/auth.go
> +			sendError(c, fmt.Errorf("Auth code not specified"), http.StatusUnauthorized)
okay

2020-09-02 14:26 UTC, ViktoriiaKovalova commented on cmd/server/auth.go
> +	token := request.Header["Authorization"]
yes, I also thought that we should add some type, but i'm not sure how to make it in /auth request, when auth code is sent. Should i also set the type to Bearer or maybe we can pass it as query parameter?

2020-09-02 14:39 UTC, ViktoriiaKovalova commented on cmd/server/list.go
> +		handler, loaded := listRequestsInProcess.LoadOrStore(user.email, &listRequestHandler{service: user.service, numConcurrentCalls: defaultNumConcurrentCalls})
Do you think I should add some checks in `GetResult()` method also? Right now the best i can think of is adding a comment that it should not be called before `GetProgress()` returns equal values(i.e. `done==all`).

2020-09-02 15:02 UTC, minorczyka commented on cmd/server/list.go
> +		handler, loaded := listRequestsInProcess.LoadOrStore(user.email, &listRequestHandler{service: user.service, numConcurrentCalls: defaultNumConcurrentCalls})
You're right, my example won't happen but modifying not thread-safe object from multiple threads is something you don't want to do no matter what. Even if right now it would work, it will be very easy to introduce some related bugs in the future and race condition bugs are very hard to debug.

2020-09-02 15:03 UTC, minorczyka commented on cmd/server/list.go
> +		handler, loaded := listRequestsInProcess.LoadOrStore(user.email, &listRequestHandler{service: user.service, numConcurrentCalls: defaultNumConcurrentCalls})
I wouldn't expose these objects outside this map, I would build more complex structure for it that would do all necessary synchronization.

2020-09-02 15:05 UTC, minorczyka commented on cmd/server/auth.go
> +	token := request.Header["Authorization"]
Oh I overlooked it. But I think in /auth request you won't get authorization code from header but from query parameter anyway.

2020-09-02 15:27 UTC, minorczyka requested changes

2020-09-02 15:27 UTC, minorczyka commented on cmd/server/auth.go
> +		c.JSON(http.StatusOK, gin.H{"token": token})
It shouldn't return token in JSON, it should redirect user to our frontend with token set in query parameter. But we still don't have handlers for frontend so I guess it can stay like that, just add some comment here.

2020-09-02 15:34 UTC, ViktoriiaKovalova commented on cmd/server/auth.go
> +		c.JSON(http.StatusOK, gin.H{"token": token})
why shouldn't it? it's auth code exchange to token, it doesn't redirect to google login page

2020-09-03 09:22 UTC, minorczyka commented on cmd/server/auth.go
> +		c.JSON(http.StatusOK, gin.H{"token": token})
Google login page will redirect user's browser to this handler (with authorization code as parameter). If you return token as JSON here, it will just be displayed in user's browser. Instead we should redirect user to page with our frontend and pass token as query parameter.

2020-09-03 15:41 UTC, ViktoriiaKovalova commented on cmd/server/auth.go
> +		c.JSON(http.StatusOK, gin.H{"token": token})
i don't know if the frontend will handle redirection so i created this /redirect handler which should return the auth code to frontend. The call to /auth for token is not a redirect right now so I am sending token in the body as a response. We can change it to something else, just tell me how it should be done, and i'll update design doc & code.

2020-09-07 15:03 UTC, minorczyka requested changes

2020-09-07 15:03 UTC, minorczyka commented on cmd/server/auth.go
> +		c.JSON(http.StatusOK, gin.H{"token": token})
It won't work but let's merge it as it's now. We will change it later when we will do integration with frontend.

2020-09-07 15:12 UTC, ViktoriiaKovalova commented on cmd/server/auth.go
> +	if len(token) != 2 || token[0] != "Bearer" {
you're right, thanks

2020-09-08 09:34 UTC, minorczyka approved these changes

2020-09-08 09:34 UTC, minorczyka commented on cmd/server/auth.go
> +	log.Println(len(bearToken))
Please remove.

2020-09-08 11:03 UTC, merged