Frontend better fetch
googleinterns/recomator pull request #129
Opened 2020-08-27 11:00 UTC by s17k

2020-08-27 16:07 UTC, s17k commented on frontend/src/store/recommendations.ts
> +  // It is safe to add to/clear the recommendations list during execution,
Maybe it was not such a good idea to put `await`s inside a forEach after all.
From what I understand, it doesn't actually handle the requests one by one. It only sends them one by one.

2020-08-27 17:28 UTC, minorczyka requested changes
Sorry that I put comments instead of review.

2020-08-27 18:23 UTC, s17k commented
> Are you sure it's fine? `forEach` uses async function so I can imagine that `state.recommendations` can be modified when `forEach` waits for `await dispatch("watchStatusOnce", rec)`.

This has been resolved already, as we discussed.

> It's not obvious that this is never ending loop. If it's meant to be called only once maybe it shouldn't be store's action and just a normal function.

https://github.com/googleinterns/recomator/pull/129/commits/ed0f471bd52db2c491ed181656e0974b02596b49

2020-08-28 13:14 UTC, s17k commented
Just letting you know that I have added the tests and this PR should be complete and ready to review now.

2020-08-28 17:25 UTC, minorczyka approved these changes

2020-08-28 18:11 UTC, merged