Frontend resource link
googleinterns/recomator pull request #154
Opened 2020-09-03 15:10 UTC by s17k

2020-09-04 04:26 UTC, brzezinski requested changes
please fix

2020-09-04 04:26 UTC, brzezinski commented on frontend/src/components/ResourceCell.vue
> +    <a :href="pantheonLink"> {{ shortName }} </a>
please do not refer to internal console name Pantheon. Instead please use "console"

2020-09-04 04:26 UTC, brzezinski commented on frontend/src/components/ResourceCell.vue
> +import { getResourcePantheonLink } from "../store/data_model/recommendation_raw";
same as above. Avoid "pantheon"

2020-09-04 04:26 UTC, brzezinski commented on frontend/src/store/data_model/recommendation_raw.ts
> +  return recommendation.content.operationGroups[0].operations[1].resource;
is there a chance there will be no second operation? any error handling?

2020-09-04 04:26 UTC, brzezinski commented on frontend/src/store/data_model/recommendation_raw.ts
> +export function extractFromResource(
any comment would be nice to have what are you extracting here

2020-09-04 04:26 UTC, brzezinski commented on frontend/src/store/data_model/recommendation_raw.ts
> +      return `https://pantheon.corp.google.com/compute/disksDetail/zones/${zone}/disks/${shortName}?project=${project}`;
it's internal link. outside world link is console.cloud.google.com

2020-09-04 04:26 UTC, brzezinski commented on frontend/tests/unit/recommendations.spec.ts
> +      "https://pantheon.corp.google.com/compute/instancesDetail/zones/us-east1-b/instances/alicja-test?project=rightsizer-test"
this link will only work in corp network

2020-09-07 08:33 UTC, s17k commented on frontend/src/store/data_model/recommendation_raw.ts
> +export function extractFromResource(
There is one comment already in line 158, but I will add something more meaningful.

2020-09-07 08:44 UTC, s17k commented on frontend/src/store/data_model/recommendation_raw.ts
> +  return recommendation.content.operationGroups[0].operations[1].resource;
It implicitly assumes that if you are asking about the second operation, you assume that it exists.
I chose not to make an error handler here because:
- we need to assume some structure of the data that we are given (for example, that no one will ask about the second resource if they did not previously check for recomender type). Returning null sometimes in some scenarios would cause more problems than it would solve; all data would be accepted and we would never probably find out about some slight inconsistencies (as the app would be always quietly handling all broken data).
- for consistency: the `getRecommendationFirstResource function` (written earlier) did not have one

2020-09-07 08:48 UTC, s17k commented
Oh wow, gj catching all of these. I had no idea Pantheon was not an official name.

2020-09-07 10:18 UTC, brzezinski approved these changes
LGTM

2020-09-07 10:45 UTC, merged