Real service tests
googleinterns/recomator pull request #160
Opened 2020-09-08 09:29 UTC by ViktoriiaKovalova

2020-09-09 15:36 UTC, minorczyka requested changes
Spawning goroutines in apply and list recommendations functions makes it much harder to test them.You can try mocking "handlers" to just test logic in "maps" but testing "handlers" will still be hard.

Side note: you can easily see that your tests are flaky (they depend on execution order and randomly fail) if you will run `go test --count=1000`

2020-09-09 15:36 UTC, minorczyka commented on cmd/server/main_test.go
> +/*
These tests are nicely done, I thought it will be problematic and maybe not worth the effort to test these endpoints. But it turned out pretty well.

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +	wait  bool // doesn't finish applying until wait is true
lines 71 and 88

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +func CheckApplyingFails(t *testing.T, info applyInfo, applyRequests *applyRequestsMap) {
okay

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +	assert.Equal(t, inProgressStatus, status.Status, "Recommendation should be in progress")
sorry, i meant it should be `being applied` now or smth like this, i'll change it.
it won't be finished because i set this wait parameter, which won't allow the request to finish before i call stopWaiting()

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +	wait  bool // doesn't finish applying until wait is true
lines 71 and 88

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +	assert.Equal(t, inProgressStatus, status.Status, "Recommendation should be in progress")
sorry, i meant it should be being applied now or smth like this, i'll change it.
it won't be finished because i set this wait parameter, which won't allow the request to finish before i call stopWaiting()

2020-09-09 15:45 UTC, minorczyka commented
There's also a problem with this PR. When you include *_test.go files in cmd/ directory, you can no longer run it with `go run *.go` command. I think we should move all files (except for simple main.go) to pkg/server/ directory. 

That was my initial idea but you started putting files into cmd/ directory and at that time it seemed to be good enough so I haven't opposed. But now it become problematic, unless you know some other way how to solve this problem.

2020-09-09 15:45 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +func CheckApplyingFails(t *testing.T, info applyInfo, applyRequests *applyRequestsMap) {
sure, i'll do it

2020-09-09 15:47 UTC, ViktoriiaKovalova commented on cmd/server/list_test.go
> +		assert.True(t, progress.BatchesProcessed < progress.NumberOfBatches, "Should not be done yet")
same here. i was using `wait` field to make sure that it will return progress first(and not result).

2020-09-09 15:48 UTC, ViktoriiaKovalova commented on cmd/server/list_test.go
> +		assert.True(t, progress.BatchesProcessed < progress.NumberOfBatches, "Should not be done yet")
so i can test that listProgressResponse is returned correctly

2020-09-09 15:51 UTC, ViktoriiaKovalova commented on cmd/server/main_test.go
> +/*
> There's also a problem with this PR. When you include *_test.go files in cmd/ directory, you can no longer run it with `go run *.go` command. I think we should move all files (except for simple main.go) to pkg/server/ directory.
> 
> That was my initial idea but you started putting files into cmd/ directory and at that time it seemed to be good enough so I haven't opposed. But now it become problematic, unless you know some other way how to solve this problem.

i do it now with ```
go build 
./server
```
but maybe it would be easier to deploy it with one main.go file that imports all our packages from github, so there will be no need to clone repository. so I can create new package if it will be better

2020-09-09 16:24 UTC, ViktoriiaKovalova commented on cmd/server/apply_test.go
> +	assert.Equal(t, inProgressStatus, status.Status, "Recommendation should be in progress")
> Spawning goroutines in apply and list recommendations functions makes it much harder to test them.You can try mocking "handlers" to just test logic in "maps" but testing "handlers" will still be hard.
> 
> Side note: you can easily see that your tests are flaky (they depend on execution order and randomly fail) if you will run `go test --count=1000`

i tried running with bigger count and it actually failed. Thanks! 
The problem was that i intended to make the same for loop in GetRecommendation() as i have in ListProjects() in list_test.go, so it would not return until `wait` is false, but i forgot :(

2020-09-28 13:10 UTC, minorczyka approved these changes

2020-09-28 15:07 UTC, merged