Progress bar made more visible now
googleinterns/recomator pull request #194
Opened 2020-09-16 17:21 UTC by s17k

- If progress is 0 (which currently usually happens for a few seconds), the progress bar is set to the indeterminate mode so that the user knows that something is happening instead of seeing a nearly blank screen.
- Changed the colour of the progress bar so that it doesn't match and blend in with the app bar

Video of how it looks now: https://screencast.googleplex.com/cast/NDYzNjYwNjE4MDg4NDQ4MHw5OWM5ZTExOS0zZg

2020-09-17 17:04 UTC, minorczyka requested changes

2020-09-17 17:04 UTC, minorczyka commented on frontend/src/views/Home.vue
> +          style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);"
Can you add class here and this style to the <style> element at the bottom of the file?

2020-09-17 17:05 UTC, s17k commented on frontend/src/views/Home.vue
> +          style="position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);"
Sure

2020-09-17 17:30 UTC, brzezinski approved these changes
LGTM

2020-09-17 17:35 UTC, s17k commented
I don't understand why, but Github doesn't allow me to merge yet: "Merging can be performed automatically once the requested changes are addressed.", even though Kamil approved 😮

2020-09-18 09:58 UTC, brzezinski approved these changes

2020-09-18 10:17 UTC, minorczyka approved these changes

2020-09-18 10:17 UTC, merged