Frontend project selection
googleinterns/recomator pull request #195
Opened 2020-09-17 09:27 UTC by Podkamienna

2020-09-17 09:30 UTC, s17k commented on frontend/src/components/CoreTable.vue
>    }
I couldn't guess why this has been added. Could you explain ?

2020-09-17 09:31 UTC, s17k commented on frontend/src/components/ProjectList.vue
> +            depressed
:(

2020-09-17 09:52 UTC, s17k requested changes

2020-09-17 09:52 UTC, s17k commented on frontend/src/components/ProjectList.vue
> +            depressed
:(

2020-09-17 09:52 UTC, s17k commented on frontend/src/components/ProjectsWithRequirements.vue
> +  requirementList = [
Is there a difference between these and the headers ? If not, why not only store these once ?

Maybe move these to a ts file somewhere in the store ? Importing from Vue files is not possible/is an unnecessary pain and someone might want to reuse. It would also be nice to just have them in a nice small file.

2020-09-17 09:52 UTC, s17k commented on frontend/src/config.ts
> +  public static DEVELOPMENT_BACKEND_ADDRESS = "http://localhost:8000";
nit: we don't need to change this

2020-09-17 09:52 UTC, s17k commented on frontend/src/store/requirements_store.ts
> +import router from "@/router";
This makes a circular dependency.
Router already imports the root store which imports this store, so you can use the router reference saved in the root store.

2020-09-17 09:52 UTC, s17k commented on frontend/src/main.ts
>  new Vue({
Please don't delete that, it is there so that we don't import the router in store files (which are... imported by the router).

2020-09-17 10:00 UTC, Podkamienna commented on frontend/src/main.ts
>  new Vue({
Ok, I deleted that, because I didn't understand what it was doing and I couldn't build the project with it.

2020-09-17 16:21 UTC, Podkamienna commented on frontend/src/components/ProjectsWithRequirements.vue
> +  requirementList = [
Yes, I plan to move them. There is a task for it in the backlog actually. But I think we decided that this is not very urgent.

2020-09-18 08:27 UTC, s17k requested changes

2020-09-18 08:27 UTC, s17k commented on frontend/src/router/index.ts
> +    path: "/recommendations",
It is hard to figure out just by name what is the difference between /recommendations and / routes (once you know that / is the table with recommendations).
I also don't get why is this a new route, please just move these back to HomeWithInit. If you don't want to start the central status watcher twice, just check if it exists first and only start it if it doesn't. That should be fine.

2020-09-18 08:46 UTC, s17k commented on frontend/src/store/projects_store.ts
> +      context.commit("setError", {
setError is not a mutation

2020-09-18 08:48 UTC, s17k commented on frontend/src/router/index.ts
> +    }
Can't we just fetch projects when we need them ? If we are already entering this page, we must have already done some project selection anyway.

2020-09-18 08:53 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    path: "/recommendations",
But why is HomeWithInit necessary?

2020-09-18 08:53 UTC, s17k commented on frontend/src/store/recommendations_store.ts
> +    if (responseJson.recommendations !== null) {
I remember that the backend returns a null instead of [] so this is actually needed unforuntately. It would be good to add this as an issue in the backend and put a TODO here to remove this once it is resolved.

2020-09-18 08:56 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    }
I don't understand why do you think so?

2020-09-18 08:57 UTC, Podkamienna commented on frontend/src/store/recommendations_store.ts
> +    if (responseJson.recommendations !== null) {
I am not sure, but maybe an empty array in Go is the same as nil.

2020-09-18 09:02 UTC, s17k commented on frontend/src/router/index.ts
> +    path: "/recommendations",
Let's imagine that we add some graphs or anything that doesn't actually require a reload of recommendations.
Then, we would like to return to Home without initialising recommendations and starting the status watcher. So instead of redirecting to HomeWithInit, they can redirect directly to Home.
Now, in the case of projects/requirements, we always want to reload all the recommendations so it might actually seem like this between Home and HomeWithInit might be unnecessary.

2020-09-18 09:03 UTC, Podkamienna commented on frontend/src/store/recommendations_store.ts
> +    if (responseJson.recommendations !== null) {
Ok, empty slice should be encoded as [] in JSON

2020-09-18 09:04 UTC, Podkamienna commented on frontend/src/store/recommendations_store.ts
> +    if (responseJson.recommendations !== null) {
I guess an empty slice shold be encoded as [] is JSON.

2020-09-18 09:07 UTC, s17k commented on frontend/src/router/index.ts
> +    }
/ (Home) is to be entered in two cases:
- someone just typed our address, so if they don't have a token, let's redirect to Google Sign in
- we have already initialised everything (for example, in HomeWithInit) and we want to show it (either for the first time, or maybe again if we have just shown some graphs)

2020-09-18 09:10 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    path: "/recommendations",
But in that case we would probably have a Home page, where you can select if you want to see some graphs or recommendations.

2020-09-18 09:11 UTC, s17k commented on frontend/src/store/recommendations_store.ts
> +    if (responseJson.recommendations !== null) {
Fair point, that is indeed how seems to be.
Imo the backend should fix it (as if we fix it in the backend not frontend, we will have a simpler interface) but it's not a huge deal. I would still put it in the backlog.

2020-09-18 09:14 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    }
So in my understanding this app currently is working so that the user needs to select projects before getting recommendations. And instead of checking on the home page if the projects were chosen already and if not redirecting to project selection page, I decided to have project selection on the home page and then redirect to the page with recommendations. Do you think that is a bad design? Why?

2020-09-18 09:17 UTC, s17k commented on frontend/src/router/index.ts
> +    path: "/recommendations",
I guess the name Home is slightly misleading, we don't have a typical Home that acts as a navigation page (links to sub-pages you can open).
If we added graphs, we would put a link to them maybe in the upper app bar or somewhere near the table. But, we would still put recommendations table in '/'. If you go to [bbc.co.uk](http://www.bbc.co.uk), you don't just get links to "Sports", "World news" and "Entertainment". You also get some actual news :)

2020-09-18 09:28 UTC, s17k commented on frontend/src/router/index.ts
> +    }
Totally agree, we want the user to select projects before getting recommendations.
But, there is a reason that BBC doesn't have sign-in at /, they just put the news there as that is the actual core of their app.

2020-09-18 09:32 UTC, s17k commented on frontend/src/views/Recommendations.vue
> +    <v-app-bar app color="primary" dark>
It would be nice not to have this code duplicated across views. What if we decide to change the colour or add a button there ?

2020-09-18 09:38 UTC, Podkamienna commented on frontend/src/views/Recommendations.vue
> +    <v-app-bar app color="primary" dark>
Yes but that is probably something for a different PR.

2020-09-18 09:39 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    }
But we don't have sign in at /? Also they don't need sign in to display the news. And they don't need selecting cities to display only news for those cities.

2020-09-18 09:40 UTC, s17k commented on frontend/src/views/Recommendations.vue
> +    <v-app-bar app color="primary" dark>
I disagree, you would have added less code by making this into a component :)

2020-09-18 09:49 UTC, s17k commented on frontend/src/router/index.ts
> +    }
Okay, let me try differently:

There is a benefit to designing the home page so that we redirect if we don't have something and then come back to it. This way you don't enforce a strict order of views and it makes it much easier to focus on what do we actually do, as the Home handler will look something like this:
- no token, get a token and come back
- no project selected, ask the user to select some projects, come back
... (maybe other stuff at some point)
So, instead of a strict order of views that is hard to follow (you would need to look at next() calls all over Home.vue), you would have a list of ifs.

2020-09-18 09:53 UTC, Podkamienna commented on frontend/src/views/Recommendations.vue
> +    <v-app-bar app color="primary" dark>
Yes, if I thought about it before. But I came out with the idea only when I wanted to make "Recomator" a button, so I would be deleting the code. Also I think, that this could be just a nice, small PR and not confuse everyone by adding something more here.

2020-09-18 09:57 UTC, s17k commented on frontend/src/views/Recommendations.vue
> +    <v-app-bar app color="primary" dark>
that is fine, maybe add an issue then

2020-09-18 09:57 UTC, Podkamienna commented on frontend/src/router/index.ts
> +    }
But I think that the strict order of the views makes it easier to understand.

2020-09-18 15:36 UTC, minorczyka requested changes

2020-09-18 15:36 UTC, minorczyka commented on frontend/src/components/CoreTable.vue
> +      this.selectableRows.length !== 0
Shouldn't you first check if `length != 0`?

2020-09-18 15:36 UTC, minorczyka commented on frontend/src/components/ProjectsWithRequirements.vue
> +  requirementList = [
You can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment to merge `headers` with this.

2020-09-18 15:36 UTC, minorczyka commented on frontend/src/router/index.ts
> +      const projectString = window.localStorage.getItem("project_list");
It would be nice to extract it to separate dedicated function or at lest not use literal string "project_list" but some constant.

2020-09-18 17:22 UTC, s17k commented on frontend/src/components/CoreTable.vue
> +      this.selectableRows.length !== 0
It doesn't matter, every returns true for empty arrays: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

2020-09-21 12:41 UTC, s17k commented on frontend/src/router/index.ts
> +      if (projectString === null) {
What if it is undefined?

2020-09-21 12:42 UTC, s17k commented on frontend/src/router/index.ts
> +      if (projectString === null) {
That is actually way more probable. localStorage getItem returns undefined if there is no key with such value

2020-09-21 12:44 UTC, s17k commented on frontend/src/store/recommendations_store.ts
> +    console.log(context.rootGetters["selectedProjects"]);
You would have probably found it on your own, but let's make sure :)

2020-09-21 12:47 UTC, s17k commented on frontend/src/views/Home.vue
> +    this.$store.commit("projectsStore/setSelected", [], {root: true});
What is `{root: true}` doing ?

2020-09-21 12:56 UTC, Podkamienna commented on frontend/src/router/index.ts
> +      if (projectString === null) {
I'm not sure, when I check in my browser's console it returns null.

2020-09-21 12:58 UTC, Podkamienna commented on frontend/src/router/index.ts
> +      if (projectString === null) {
https://developer.mozilla.org/en-US/docs/Web/API/Storage/getItem

2020-09-21 12:59 UTC, s17k commented on frontend/src/router/index.ts
> +      if (projectString === null) {
You are right! My bad.

2020-09-21 13:02 UTC, Podkamienna commented on frontend/src/views/Home.vue
> +    this.$store.commit("projectsStore/setSelected", [], {root: true});
I guess that it is not necessary here, but what it does is calling a mutation as if the store it is called on was the root of the store. So you can call something from projectsStore, when having recommendationsStore.

2020-09-21 13:07 UTC, s17k commented on frontend/src/views/Home.vue
> +    this.$store.commit("projectsStore/setSelected", [], {root: true});
yeah, you don't need it here then. I didn't know that there is such an option, cool!

2020-09-21 15:38 UTC, s17k commented
It would be amazing if you could post some screenshots, as you are adding a lot of new UI.
I will run this on my own as well, but it would be easier to discuss if everyone had it easily visible.

2020-09-21 15:47 UTC, s17k commented on frontend/src/components/ProjectsWithRequirements.vue
> +
I have some ideas how to simplify this:
```typescript
headers = [
   {value:"name"}, 
    this.requirementList..map(reqName => {value: reqName, align: "center" })
];
   ```

2020-09-21 15:53 UTC, s17k requested changes

2020-09-21 15:53 UTC, s17k commented on frontend/tests/unit/home_view.spec.ts
> +import Recommendation from "@/views/Home.vue";
I think this should stay as 'Home' :)

2020-09-22 05:10 UTC, Podkamienna commented
![image](https://user-images.githubusercontent.com/46993440/93845853-956be880-fca2-11ea-8ff0-cdd3b7fb7143.png)

2020-09-22 05:15 UTC, Podkamienna commented
![image](https://user-images.githubusercontent.com/46993440/93846068-483c4680-fca3-11ea-88c4-cb183cc33c0d.png)

2020-09-22 05:18 UTC, Podkamienna commented
![image](https://user-images.githubusercontent.com/46993440/93846116-715cd700-fca3-11ea-976c-b5afdf11a2ac.png)

2020-09-22 05:18 UTC, Podkamienna commented
![image](https://user-images.githubusercontent.com/46993440/93846234-c4368e80-fca3-11ea-887d-47ba3bc2b291.png)

2020-09-22 07:35 UTC, s17k commented
There is no nice way to stop fetching once we start it. So, imo the settings button should not be there when the recommendations are still being fetched.

2020-09-22 07:45 UTC, s17k commented
I am writing this app and it took me a while to figure out what "recommendations" and "requirements" buttons actually do. I would vote for naming them: 
- "See permissions" or "Permissions table" 
- "Confirm" or "OK" or "Finish"

2020-09-22 07:45 UTC, s17k commented
Also, let's maybe disable the requirements/recommendations buttons if there are no selected projects, to make this more intuitive ?

2020-09-22 08:21 UTC, Podkamienna commented
But if there was no setting button, then if someone added a new project and wanted to check if there is some recommendation for it, they would have to wait for all the recommendations to be fetched, which could take quite a long time. It actually didn't occur to me, that it could not work. But you are right and the simplest way to fix it is not allowing users to change the project while loading. I don't really like it though.

2020-09-22 08:25 UTC, s17k commented
They can just reload the whole page if they like :), so it's not like they absolutely need to wait once they choose their projects.

2020-09-22 08:55 UTC, Podkamienna commented
If they reload the page, they will have to wait anyway, as the selected projects are saved in the localstorage. What they could do is clearing the localstorage.

2020-09-22 12:46 UTC, Podkamienna commented
Updated photos of UI:
![image](https://user-images.githubusercontent.com/46993440/93878344-332eda00-fcda-11ea-9af8-7ea68e91fbf3.png)
![image](https://user-images.githubusercontent.com/46993440/93878422-578ab680-fcda-11ea-9340-055ca78ce3e8.png)
![image](https://user-images.githubusercontent.com/46993440/93879246-aedd5680-fcdb-11ea-80af-859bc997e93b.png)
![image](https://user-images.githubusercontent.com/46993440/93881919-c74f7000-fcdf-11ea-8b4b-f6117d863e8c.png)

2020-09-22 13:15 UTC, s17k commented
Looks good. 
I would only vote for putting the black buttons together on the right, instead of having them spread out and centered.

2020-09-22 13:19 UTC, s17k commented on frontend/src/components/ProjectsWithRequirements.vue
> +  headers = ([] as { value: string; align?: string }[]).concat(
I think we can just use "as" on the first element `[{value: "name"}]` and avoid using concat.

2020-09-22 13:31 UTC, s17k commented on frontend/src/components/AppBar.vue
> +
Missing @Component

2020-09-22 13:34 UTC, s17k requested changes
Please fix :)

2020-09-22 13:34 UTC, s17k commented on frontend/src/components/AppBar.vue
> +
Missing `@Component` results in an error when I tried running this code on my own.

2020-09-22 13:39 UTC, Podkamienna commented on frontend/src/components/AppBar.vue
> +
I'm sorry, I managed not to push my changes somehow, it should work now.

2020-09-22 15:45 UTC, minorczyka approved these changes

2020-09-22 15:45 UTC, minorczyka commented on frontend/src/store/requirements_store.ts
> +      }
We should handle errors similarly to how it's done in Stan's new PR (https://github.com/googleinterns/recomator/pull/203). But it can stay as it is for now, let's do it in the later PR.

2020-09-23 07:41 UTC, s17k approved these changes

2020-09-23 09:23 UTC, merged