New error page, authFetch handles failed requests
googleinterns/recomator pull request #203
Opened 2020-09-21 20:12 UTC by s17k

2020-09-22 15:33 UTC, minorczyka requested changes

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/components/ErrorMsg.vue
> +  }
It's better to make `openedIndices` just a computed property (getter).

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/router/misc.ts
> +    await fetch(`${getBackendAddress()}/auth?code=123`);
Maybe we could call `/redirect` endpoint. So we don't make any unnecessary calls to Google APIs.

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/router/show_error.ts
> +  window.location.assign(`/errorMsg?header=${headerParam}&body=${bodyParam}`);
We should encode this parameters (and later in router decode), we can't just pass these strings directly (https://en.wikipedia.org/wiki/Query_string).

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/store/auth/auth_fetch.ts
> +        await delay(2000);
It's a good practice to use exponential backoff for retires (https://en.wikipedia.org/wiki/Exponential_backoff), e.g. for the first time we wait 2s, for the second time 4s, for the third time 8s etc.

If a service is having issues caused by a large amount of traffic, adding retires to clients makes things even worse. It works as a positive feedback which can potentially completely kill the service.

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/store/auth/auth_fetch.ts
> +            "Stack trace": error.stack
In general you don't want to show stack trace to users, only log it somewhere. But if your audience is programmers then it might make some sense (some of our internal tools does it), it's also easier to report bugs.

I'm just not sure how the stack trace will look for minified JS code. You will need source maps to make any sense from them.

2020-09-22 15:33 UTC, minorczyka commented on frontend/src/store/auth/auth_fetch.ts
> +        await delay(infiniteDurationMs);
That's a little dirty hack :smile:

2020-09-22 15:38 UTC, s17k commented on frontend/src/store/auth/auth_fetch.ts
> +            "Stack trace": error.stack
I was thinking something like: the user gets an error, makes an issue (ticket) and attaches the screenshot (with stack trace). So you don't even need to be a developer to make use of it.

2020-09-22 15:46 UTC, s17k commented on frontend/src/router/misc.ts
> +    await fetch(`${getBackendAddress()}/auth?code=123`);
That was my first idea, but once you do that it actually redirects your requests to a google sign-in page which makes some failed requests.

It does actually make Google API calls, I didn't think about that. Nice catch.
I will just change it to `/recommendations` which responds with `Authorization header not in the form 'Bearer...` so the backend will probably not be doing any Google API calls (which also makes sense, I guess it just checks if the token is present in memory).

2020-09-22 15:47 UTC, s17k commented on frontend/src/store/auth/auth_fetch.ts
> +        await delay(2000);
Yep, fair point.

2020-09-22 15:47 UTC, minorczyka commented on frontend/src/router/misc.ts
> +    await fetch(`${getBackendAddress()}/auth?code=123`);
I thought it won't make redirection if we call it just with fetch, I'm surprised. But `/recommendaitons` without auth headers also sounds good.

2020-09-22 15:48 UTC, minorczyka commented on frontend/src/store/auth/auth_fetch.ts
> +            "Stack trace": error.stack
Sounds good, it can stay.

2020-09-22 16:10 UTC, s17k commented on frontend/src/router/show_error.ts
> +  window.location.assign(`/errorMsg?header=${headerParam}&body=${bodyParam}`);
Yes, I was really worried about that. But it magically got encoded (I saw the browser address) and decoded without anything explicit so I gave in.

2020-09-22 16:13 UTC, s17k commented on frontend/src/components/ErrorMsg.vue
> +  }
It's a two-way binding though.

2020-09-23 16:35 UTC, minorczyka approved these changes

2020-09-23 16:35 UTC, minorczyka commented on frontend/src/components/ErrorMsg.vue
> +  }
Ok, I haven't noticed.

2020-09-24 09:05 UTC, merged