add cloud build
googleinterns/recomator pull request #226
Opened 2020-10-01 09:50 UTC by ViktoriiaKovalova

2020-10-05 09:25 UTC, minorczyka requested changes

2020-10-05 09:25 UTC, minorczyka commented on .gcloudignore
> -frontend/
Uploading `frontend` directory is unnecessary, especially I would like to make sure that we won't upload `node_modules` directory because it's very heavy.

2020-10-05 09:25 UTC, minorczyka commented on deploy_gcloudignore.txt
> +!frontend/dist
What's the reason for having it in separate file?

2020-10-05 09:41 UTC, ViktoriiaKovalova commented on deploy_gcloudignore.txt
> +!frontend/dist
first, l it's used by cloud build (it creates config.json and .env file with backend address from Secret Manager API, then builds frontend). at this point we need /frontend folder.
then, cloud build goes to deployment step(running gcloud app deploy) and we don't need frontend/ folder, so we need to update .gcloudignore
So, the point is .gcloudignore is used 2 times and at the first time we need frontend folder, at the second time - not. So .gcloudignore is updated after frontend is built.

2020-10-05 09:43 UTC, ViktoriiaKovalova commented on deploy_gcloudignore.txt
> +!frontend/dist
You can see lines 17-25 of cloudbuild.yaml  - it's the step which updates .gcloudignore

2020-10-05 09:45 UTC, ViktoriiaKovalova commented on .gcloudignore
> -frontend/
we don't upload it to app engine, it's the .glcoudignore which is used when cloning repository for build

2020-10-05 09:48 UTC, minorczyka commented on deploy_gcloudignore.txt
> +!frontend/dist
When Cloud Build clones repository it removes files that are present in `.cloudignore`?

2020-10-06 08:56 UTC, minorczyka approved these changes

2020-10-06 09:17 UTC, merged