Retry quota exceeded
googleinterns/recomator pull request #234
Opened 2020-10-06 08:43 UTC by ViktoriiaKovalova

2020-10-07 14:24 UTC, minorczyka requested changes

2020-10-07 14:24 UTC, minorczyka commented on pkg/automation/disks.go
> +	})
You can make `DoRequestWithRetries` return an error, it will make writing this code a little bit more cleaner, you won't have to define `var err` and will be able to return err without assignment in the lambda.

2020-10-08 09:01 UTC, ViktoriiaKovalova commented on pkg/automation/disks.go
> +	})
I don't know how to do it:
```
var response *serviceusage.GoogleApiServiceusageV1Service
		err := DoRequestWithRetries(func() error {
			response, err := servicesService.Get("projects/" + project + "/services/" + api).Do()
			return err
		})
```
this way i get:
```
../../pkg/automation/access.go:52:4: response declared but not used
```
And this way:
```
var response *serviceusage.GoogleApiServiceusageV1Service
		err := DoRequestWithRetries(func() error {
			response, err = servicesService.Get("projects/" + project + "/services/" + api).Do()
			return err
		})
```
I get
```
../../pkg/automation/access.go:52:14: undefined: err
../../pkg/automation/access.go:53:11: undefined: err
```

2020-10-08 10:01 UTC, minorczyka commented on pkg/automation/disks.go
> +	})
In this case it will really be change for worse. You will have to do it like:
```
var response *serviceusage.GoogleApiServiceusageV1Service
err := DoRequestWithRetries(func() error {
	resp, err := servicesService.Get("projects/" + project + "/services/" + api).Do()
	response = resp
	return err
})
```

2020-10-08 13:32 UTC, ViktoriiaKovalova commented
@minorczyka there's a test checking that after receiving some error codes(302, 405, 503) frontend will retry, what should I do with it?

2020-10-09 09:33 UTC, minorczyka approved these changes

2020-10-09 10:17 UTC, merged